apiVersion: core.choreo.dev/v1
kind: DeploymentPipeline
metadata:
  annotations:
    core.choreo.dev/description: Standard deployment pipeline with dev, staging, and
      prod environments
    core.choreo.dev/display-name: Default Pipeline
  labels:
    core.choreo.dev/name: default-pipeline
  name: default-pipeline
spec:
  promotionPaths:
    - sourceEnvironmentRef: development
      targetEnvironmentRefs:
        - name: staging
          requiresApproval: false
        - isManualApprovalRequired: true
          name: production
    - sourceEnvironmentRef: staging
      targetEnvironmentRefs:
        - name: production
          requiresApproval: true
