namespace: default-org

resources:
  - hack
#  - dataplanes
#  - deployment-pipelines
#  - environments
  - configuration-groups
  - projects

labels:
  - pairs:
      core.choreo.dev/organization: default-org

