apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buildplans.core.choreo.dev
spec:
  conversion:
    strategy: None
  group: core.choreo.dev
  names:
    kind: BuildPlan
    listKind: BuildPlanList
    plural: buildplans
    singular: buildplan
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: { }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploymentprofiles.core.choreo.dev
spec:
  conversion:
    strategy: None
  group: core.choreo.dev
  names:
    kind: DeploymentProfile
    listKind: DeploymentProfileList
    plural: deploymentprofiles
    singular: deploymentprofile
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: { }
---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imageimports.core.choreo.dev
spec:
  conversion:
    strategy: None
  group: core.choreo.dev
  names:
    kind: ImageImport
    listKind: ImageImportList
    plural: imageimports
    singular: imageimport
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: { }
