apiVersion: core.choreo.dev/v1
kind: DeploymentProfile
metadata:
  name: reading-list-service-deployment-profile-1
  annotations:
    core.choreo.dev/display-name: Deployment Profile for Reading List Service
    core.choreo.dev/description: Deployment profile for the Reading List Service
  labels:
    core.choreo.dev/name: reading-list-service-deployment-profile-1
spec:
  configuration:
    endpointTemplates:
      - metadata:
          name: reading_list
        spec:
          service:
            basePath: /api/v1/reading-list
            port: 8080
          type: REST
          schemaFilePath: docs/openapi.yaml
