apiVersion: core.choreo.dev/v1
kind: DeploymentTrack
metadata:
  name: reading-list-service-main
  annotations:
    core.choreo.dev/display-name: Main deployment track
    core.choreo.dev/description: The main deployment track for the reading-list-service component
  labels:
    core.choreo.dev/name: reading-list-service-main
spec:
  buildTemplateSpec:
    branch: main
    path: /go-reading-list-rest-api
    buildConfiguration:
      buildpack:
        name: Go
        version: 1.x
