
resources:
  - ../../base


nameSuffix: -staging

labels:
  - pairs:
      core.choreo.dev/environment: staging
      core.choreo.dev/name: reading-list-webapp-staging

patches:
  - target:
      group:  core.choreo.dev
      version: v1
      kind:   Deployment
      name:   reading-list-webapp-deployment
    path: deployment.yaml
