apiVersion: core.choreo.dev/v1
kind: ConfigurationGroup
metadata:
  name: github
  annotations:
    core.choreo.dev/display-name: GitHub Configuration
    core.choreo.dev/description: GitHub configuration for the main repository
  labels:
    core.choreo.dev/name: github
spec:
  environmentGroups:
    # Define an environment groups that includes all environments for environment independent configurations
    # This helps to avoid duplication of configurations across environments when writing the YAML.
    # You can define these same configurations for each environment separately if needed.
    - environments:
        - development
        - staging
        - production
      name: all-environments
  configurations:
    - key: repository
      values:
        - environmentGroupRef: all-environments
          value: "https://github.com/openchoreo/openchoreo"
    - key: pat
      # Define GitHub Personal Access Token (PAT) Key Vault reference for each environment
      # The vaultKey is the path to the secret in the vault.
      values:
        - environment: development
          vaultKey: "secret/data/dev/github/pat"
        - environment: staging
          vaultKey: "secret/data/stg/github/pat"
        - environment: production
          vaultKey: "secret/data/prod/github/pat"
