apiVersion: core.choreo.dev/v1
kind: BuildPlan
metadata:
  name: reading-list-service-build-plan-4061be9
  annotations:
    core.choreo.dev/display-name: Build for Reading List Service
    core.choreo.dev/description: Build triggered for the Reading List Service
  labels:
    core.choreo.dev/name: reading-list-service-build-plan-4061be9
spec:
  ref:
    commit: 4061be9
#    branch: main
#    tag: v0.2.0
  path: /go-reading-list-rest-api
  buildConfiguration:
    buildpack:
      name: Go
      version: 1.x
  deploymentProfileRef: reading-list-service-deployment-profile-1
